/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

import org.junit.Test;
import static org.junit.Assert.*;

public class FizzBuzzTest {
    @Test public void knowsWhenNumberIsDivisibleByThree() {
        FizzBuzz fizzbuzz = new FizzBuzz();

        assertEquals(true, fizzbuzz.isDivisibleByThree(3));
    }

    @Test public void knowsWhenNumberIsNotDivisibleByThree() {
      FizzBuzz fizzbuzz = new FizzBuzz();

      assertEquals(false, fizzbuzz.isDivisibleByThree(1));
  }
}
