/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

public class FizzBuzz {

    public boolean isDivisibleByThree(Integer number) {
        return number % 3 == 0;
    }
}
